kind: pipeline
type: docker
name: default

steps:
  - name: lint
    image: golangci/golangci-lint:v1.60.1-alpine
    environment:
      GOCACHE: /cache
      GOLANGCI_LINT_CACHE: /cache
      GOMODCACHE: /cache/mod
      GOPATH: /go
    volumes:
      - name: gocache
        path: /cache
    commands:
      - go env -w GO111MODULE=on
      - go env -w GOPROXY=https://goproxy.cn,direct
      - go mod download
      - golangci-lint run -v --timeout 5m
    when:
      event:
        exclude:
          - pull_request
          - tag

  - name: wait-for-docker-dind
    image: docker:27-cli
    volumes:
      - name: dockersock
        path: /var/run
    commands:
      - sleep 5
      - until docker ps -a; do sleep 1; done
      - echo "Docker is ready"
    depends_on:
      - lint
    when:
      event:
        - tag

  - name: build
    image: docker:27-cli
    volumes:
      - name: dockersock
        path: /var/run
    environment:
      DOCKER_HUB_USERNAME:
        from_secret: docker_hub_username
      DOCKER_HUB_TOKEN:
        from_secret: docker_hub_token
    commands:
      - echo $DOCKER_HUB_TOKEN | docker login -u $DOCKER_HUB_USERNAME --password-stdin
      - docker build --build-arg "VERSION=${DRONE_TAG}" -t "$${DOCKER_HUB_USERNAME}/rss-zero:${DRONE_TAG##v}" -f docker/Dockerfile.server .
      - docker tag "$${DOCKER_HUB_USERNAME}/rss-zero:${DRONE_TAG##v}" $${DOCKER_HUB_USERNAME}/rss-zero:latest
    depends_on:
      - wait-for-docker-dind
    when:
      event:
        - tag

  - name: publish
    image: docker:27-cli
    volumes:
      - name: dockersock
        path: /var/run
    environment:
      DOCKER_HUB_USERNAME:
        from_secret: docker_hub_username
      DOCKER_HUB_TOKEN:
        from_secret: docker_hub_token
    commands:
      - echo $DOCKER_HUB_TOKEN | docker login -u $DOCKER_HUB_USERNAME --password-stdin
      - |
        docker images $${DOCKER_HUB_USERNAME}/rss-zero --format "{{.Repository}}:{{.Tag}}" | while read image; do
          docker push "$image"
        done
    depends_on:
      - build
    when:
      event:
        - tag

  - name: gitea_release
    image: plugins/gitea-release
    settings:
      api_key:
        from_secret: gitea_api_key
      base_url:
        from_secret: gitea_url
      prerelease: false
      draft: true
    depends_on:
      - build
    when:
      event:
        - tag

  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: ssh_host
      username:
        from_secret: ssh_username
      key:
        from_secret: ssh_password
      port: 12280
      command_timeout: 2m
      script:
        - cd /home/yip/services/rss-zero
        - sed -i "s/TAG=.*/TAG=${DRONE_TAG##v}/" .env
        - docker compose pull
        - docker compose up -d
    depends_on:
      - publish
    when:
      event:
        - tag

services:
  - name: docker
    image: docker:27-dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run
    when:
      event:
        - tag

volumes:
  - name: dockersock
    temp: {}
  - name: gocache
    host:
      path: /var/cache/drone/go
