kind: pipeline
type: docker
name: default

steps:
  - name: lint
    image: golangci/golangci-lint:v1.55-alpine
    volumes:
      - name: deps
        path: /go
    commands:
      - golangci-lint run -v --timeout 5m

  - name: build
    image: docker:24.0.7-cli
    volumes:
      - name: dockersock
        path: /var/run
    environment:
      DOCKER_REPO:
        from_secret: docker_repo
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
    commands:
      - docker build -t "$DOCKER_REPO/rss-zero:${DRONE_TAG##v}" -f docker/Dockerfile.server .
      - docker tag "$DOCKER_REPO/rss-zero:${DRONE_TAG##v}" $DOCKER_REPO/rss-zero:latest
      - echo $DOCKER_PASSWORD | docker login $REPO_HOST -u $DOCKER_USERNAME --password-stdin
      - docker run -v /var/run/docker.sock:/var/run/docker.sock $DOCKER_REPO/slim:1.40.10 build --tag "$DOCKER_REPO/rss-zero:${DRONE_TAG##v}-slim" --http-probe=false --target "$DOCKER_REPO/rss-zero:${DRONE_TAG##v}"
      - docker tag "$DOCKER_REPO/rss-zero:${DRONE_TAG##v}-slim" $DOCKER_REPO/rss-zero:latest-slim
    when:
      event:
        - tag

  - name: publish
    image: docker:24.0.7-cli
    volumes:
      - name: dockersock
        path: /var/run
    environment:
      DOCKER_REPO:
        from_secret: docker_repo
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
    commands:
      - echo $DOCKER_PASSWORD | docker login $REPO_HOST -u $DOCKER_USERNAME --password-stdin
      - |
        docker images $DOCKER_REPO/rss-zero --format "{{.Repository}}:{{.Tag}}" | while read image; do
          docker push "$image"
        done
    when:
      event:
        - tag

  - name: gitea_release
    image: plugins/gitea-release
    settings:
      api_key:
        from_secret: gitea_api_key
      base_url:
        from_secret: gitea_url
      prerelease: false
      draft: true
    depends_on:
      - build
    when:
      event:
        - tag

services:
  - name: docker
    image: docker:24.0.7-dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: dockersock
    temp: {}
