version: 2

builds:
  - id: server
    env:
      - CGO_ENABLED=0
      - GOPROXY=https://goproxy.cn,direct
    dir: ./server
    main: ./cmd/server
    ldflags:
      - -w -s -X "github.com/eli-yip/rss-zero/internal/version.Version={{ .Tag }}"
    goos: [darwin, linux]
    goarch: [arm64, amd64]
    ignore:
      - goos: darwin
        goarch: amd64
      - goos: linux
        goarch: arm64

dockers:
  - goos: linux
    goarch: amd64
    dockerfile: docker/Dockerfile.goreleaser
    image_templates:
      - "eliyip/rss-zero:{{ .Tag }}"
      - "eliyip/rss-zero:latest"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--build-arg=VERSION={{ .Tag }}"
    extra_files:
      - "webapp/dist"

archives:
  - id: server
    formats: ["tar.gz"]
    files:
      - none*
    ids:
      - server

release:
  draft: true

gitea_urls:
  api: https://gitea.darkeli.com/api/v1
  download: https://gitea.darkeli.com
