name: Release

on:
  push:
    tags: ["*"]

jobs:
  lint:
    uses: ./.gitea/workflows/lint.yaml
    secrets: inherit
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        working-directory: webapp
        run: bun install --frozen-lockfile --registry=https://registry.npmmirror.com # Use cli args here as if we use with in setup-bun, then it will create a file in git, then goreleaser will not work
      - name: Build webapp
        working-directory: webapp
        env:
          VITE_APP_VERSION: ${{ gitea.ref_name }}
        run: |
          bun run build
      # setup-go automatically cache go.mod and go.sum.
      # So we don't need use actions/cache to cache go dependencies.
      # more info: https://github.com/actions/setup-go#caching-dependency-files-and-build-outputs
      - uses: actions/setup-go@v5
        with:
          go-version: stable
          token: ${{ secrets.GH_TOKEN }}
          cache-dependency-path: |
            server/go.sum
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        env:
          GITEA_TOKEN: ${{ secrets.GITEA_TOKEN}}
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: docker pull and docker run
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script_stop: true
          script: |
            cd /home/yip/services/rss-zero
            sed -i "s/TAG=.*/TAG=${{ gitea.ref_name }}/" .env
            docker compose pull
            docker compose up -d
