name: Lint
on:
  push:
    branches:
      - "**"
  workflow_call:
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
          token: ${{ secrets.GH_TOKEN }}
          cache-dependency-path: |
            server/go.sum
      - name: use mirror
        run: go env -w GOPROXY=https://goproxy.cn,direct
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          working-directory: server
