FROM golang:1.22-alpine3.19 AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go env -w GO111MODULE=on && \
  go env -w GOPROXY=https://goproxy.cn,direct && \
  go mod download

COPY . .

RUN go build -tags="timetzdata" -o server ./cmd/server

FROM alpine:3.19

WORKDIR /app

COPY --from=builder /app/server .

RUN apk add --no-cache -U tzdata

ENV TZ=Asia/Shanghai

EXPOSE 8080

ENTRYPOINT ["./server"]
