FROM alpine:3.20

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories && \
  apk add --no-cache -U tzdata

WORKDIR /app

COPY rss-zero /app/rss-zero
COPY webapp/dist /app/dist

ENV TZ=Asia/Shanghai

EXPOSE 8080

ENTRYPOINT ["./rss-zero"]
