services:

  rss-zero:
    image: ${IMAGE}
    container_name: rss-zero
    restart: always
    expose:
      - 8080
    depends_on:
      rss-db:
        condition: service_healthy
    volumes:
      - /var/log/rss-zero:/app/logs

  rss-zhihu-encrypt:
    image: eliyip/rss-zhihu-encrypt:1.2.12
    container_name: rss-zhihu-encrypt
    restart: always
    expose:
      - 3000

  rss-db:
    image: postgres:16.3-alpine
    container_name: rss-db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    expose:
      - 5432
    volumes:
      - ./db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  rss-redis:
    image: redis:7-alpine
    container_name: rss-redis
    restart: always
    expose:
      - 6379
    volumes:
      - ./redis-data:/data