[settings]
server_url = ''
internal_server_url = ''
fresh_rss_url = ''
debug = false

[minio]
endpoint = ''
access_key_id = ''
secret_access_key = ''
bucket = ''
assets_prefix = ''

[openai]
model = ''
api_key = ''
base_url = ''

[database]
host = ''
port = ''
user = ''
password = ''
name = ''

[redis]
address = ''
password = ''

[bark]
url = ''

[zlive]
server_url = ''
username = ''
password = ''

[test_url]
zsxq = ''
zhihu = ''
xiaobot = ''

[utils]
rsshub_url = ''
